clear all;
clc;
addpath('mksqlite');
mksqlite('open','forex_predictor.db');
mksqlite('PRAGMA writable_schema = 1');
mksqlite('delete from sqlite_master where type in (''table'', ''index'', ''trigger'')');
mksqlite('PRAGMA writable_schema = 0');
mksqlite('VACUUM');
a = mksqlite('PRAGMA INTEGRITY_CHECK');
fprintf('integrity check... %s\n', a.integrity_check);