clear all;
clc;
addpath('mksqlite');
mksqlite('open','forex_predictor.db');
mksqlite(['CREATE TABLE IF NOT EXISTS x_daily (' ...
         'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
         'time DATETIME,' ...
         'ema3 DOUBLE,' ...
         'ema30 DOUBLE,' ...
         'ema15 DOUBLE,' ...
         'ema60 DOUBLE,' ...
         'sma3 DOUBLE,' ...
         'sma15 DOUBLE,' ...
         'atr3 DOUBLE,' ...
         'atr15 DOUBLE,' ...
         'adx3 DOUBLE,' ...
         'adx15 DOUBLE,' ...
         'stoch3 DOUBLE,' ...
         'stoch15 DOUBLE,' ...
         'rsi3 DOUBLE,' ...
         'rsi15 DOUBLE,' ...
         'macd DOUBLE' ...
         ')']);
mksqlite(['CREATE TABLE IF NOT EXISTS y_daily (' ...
         'id INTEGER PRIMARY KEY AUTOINCREMENT,' ...
         'time DATETIME,' ...
         'signal TINYINT,' ...
         'bid DOUBLE,' ...
         'ask DOUBLE,' ...
         'max_close DOUBLE,' ...
         'target DOUBLE' ...
         ')']);